---
title: "Create tabsets panel from R code"
format: 
    html:
      code-tools:
        source: https://github.com/quarto-dev/quarto-examples/blob/main/tabsets/tabsets-from-r-chunks
bibliography: packages.bib
---

<!-- This part is about description of the example -->

::: {.callout-note collapse="true"}

{{< include README.qmd >}}

:::

<!-- below is the example itself -->

```{r}
#| label: r-pkgs
#| include: false
library(dplyr)
library(gt)
library(purrr)
```

# Tables

::: {.panel-tabset}

```{r}
#| output: asis
#| echo: false
res <- purrr::map_chr(unique(starwars$homeworld), \(hw) {
    knitr::knit_child(
      input = "child-dir/_child.qmd", 
      envir = environment(), 
      quiet = TRUE
      )
  })

cat(res, sep = '\n')
```
:::

```{r}
#| include: false
knitr::write_bib("rmarkdown", "packages.bib")
```


## Resources

Learn more about this **knitr** feature in the R Markdown Cookbook [@rmarkdown2020], where some recipies are also applicable to Quarto:

* The section about [child document](https://bookdown.org/yihui/rmarkdown-cookbook/child-document.html)
* Going further with [`knitr::knit_expand()`](https://bookdown.org/yihui/rmarkdown-cookbook/knit-expand.html) to use with `knitr::knit_child()`